package net.hypixel.skyblock.gui;

import org.bukkit.inventory.ItemStack;
import org.bukkit.entity.Player;
import net.hypixel.skyblock.util.FerocityCalculation;
import net.hypixel.skyblock.features.skill.Skill;
import net.hypixel.skyblock.user.User;
import net.hypixel.skyblock.util.Sputnik;
import org.bukkit.DyeColor;
import org.bukkit.material.Dye;
import net.hypixel.skyblock.util.SUtil;
import net.hypixel.skyblock.user.PlayerUtils;
import net.hypixel.skyblock.user.PlayerStatistics;
import org.bukkit.Material;
import org.bukkit.ChatColor;

public class SkyBlockProfileGUI extends GUI
{
    public SkyBlockProfileGUI() {
        super("Your SkyBlock Profile", 54);
    }
    
    @Override
    public void onOpen(final GUIOpenEvent e) {
        this.fill(SkyBlockProfileGUI.BLACK_STAINED_GLASS_PANE);
        this.set(GUIClickableItem.createGUIOpenerItem(GUIType.SKYBLOCK_MENU, e.getPlayer(), (Object)ChatColor.GREEN + "Go Back", 48, Material.ARROW, (Object)ChatColor.GRAY + "To SkyBlock Menu"));
        this.set(GUIClickableItem.getCloseItem(49));
        final Player player = e.getPlayer();
        final PlayerStatistics statistics = (PlayerStatistics)PlayerUtils.STATISTICS_CACHE.get((Object)player.getUniqueId());
        Double visualcap = statistics.getCritChance().addAll() * 100.0;
        if (visualcap > 100.0) {
            visualcap = 100.0;
        }
        ItemStack itemstack = null;
        final String feroDisplay = "";
        if (statistics.getFerocity().addAll() > 0.0) {
            itemstack = SUtil.getSkullStack((Object)ChatColor.GREEN + "Your SkyBlock Profile", player.getName(), 1, (Object)ChatColor.RED + "  \u2764 Health " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getMaxHealth().addAll().intValue()) + " HP", (Object)ChatColor.GREEN + "  \u2748 Defense " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getDefense().addAll().intValue()), (Object)ChatColor.RED + "  \u2741 Strength " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getStrength().addAll().intValue()), (Object)ChatColor.WHITE + "  \u2726 Speed " + SUtil.commaify(statistics.getSpeed().addAll() * 100.0), (Object)ChatColor.BLUE + "  \u2623 Crit Chance " + (Object)ChatColor.WHITE + SUtil.commaify(visualcap.intValue()) + "%", (Object)ChatColor.BLUE + "  \u2620 Crit Damage " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getCritDamage().addAll() * 100.0) + "%", (Object)ChatColor.AQUA + "  \u270e Intelligence " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getIntelligence().addAll().intValue()), (Object)ChatColor.YELLOW + "  \u2694 Bonus Attack Speed " + (Object)ChatColor.WHITE + SUtil.commaify(Math.min(100.0, (double)statistics.getAttackSpeed().addAll())) + "%", (Object)ChatColor.DARK_AQUA + "  \u03b1 Sea Creature Chance " + (Object)ChatColor.RED + "\u2717", (Object)ChatColor.LIGHT_PURPLE + "  \u2663 Pet Luck " + (Object)ChatColor.RED + "\u2717", (Object)ChatColor.AQUA + "  \u272f Magic Find " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getMagicFind().addAll() * 100.0), (Object)ChatColor.RED + "  \u2afd Ferocity " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getFerocity().addAll().intValue()), (Object)ChatColor.RED + "  \u0e51 Ability Damage " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getAbilityDamage().addAll().intValue()) + "%");
        }
        else {
            itemstack = SUtil.getSkullStack((Object)ChatColor.GREEN + "Your SkyBlock Profile", player.getName(), 1, (Object)ChatColor.RED + "  \u2764 Health " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getMaxHealth().addAll().intValue()) + " HP", (Object)ChatColor.GREEN + "  \u2748 Defense " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getDefense().addAll().intValue()), (Object)ChatColor.RED + "  \u2741 Strength " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getStrength().addAll().intValue()), (Object)ChatColor.WHITE + "  \u2726 Speed " + SUtil.commaify(statistics.getSpeed().addAll() * 100.0), (Object)ChatColor.BLUE + "  \u2623 Crit Chance " + (Object)ChatColor.WHITE + SUtil.commaify(visualcap.intValue()) + "%", (Object)ChatColor.BLUE + "  \u2620 Crit Damage " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getCritDamage().addAll() * 100.0) + "%", (Object)ChatColor.AQUA + "  \u270e Intelligence " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getIntelligence().addAll().intValue()), (Object)ChatColor.YELLOW + "  \u2694 Bonus Attack Speed " + (Object)ChatColor.WHITE + SUtil.commaify(Math.min(100.0, (double)statistics.getAttackSpeed().addAll())) + "%", (Object)ChatColor.DARK_AQUA + "  \u03b1 Sea Creature Chance " + (Object)ChatColor.RED + "\u2717", (Object)ChatColor.LIGHT_PURPLE + "  \u2663 Pet Luck " + (Object)ChatColor.RED + "\u2717", (Object)ChatColor.AQUA + "  \u272f Magic Find " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getMagicFind().addAll() * 100.0), (Object)ChatColor.RED + "  \u0e51 Ability Damage " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getAbilityDamage().addAll().intValue()) + "%");
        }
        this.set(4, itemstack);
        this.set(19, SUtil.getStack((Object)ChatColor.RED + "\u2764 Health " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getMaxHealth().addAll().intValue()) + " HP", Material.GOLDEN_APPLE, (short)0, 1, (Object)ChatColor.GRAY + "Health is your total maximum", (Object)ChatColor.GRAY + "health. Your natural", (Object)ChatColor.GRAY + "regeneration gives " + (Object)ChatColor.GREEN + SUtil.commaify(Math.round(statistics.getMaxHealth().addAll() * 0.01)) + " HP", (Object)ChatColor.GRAY + "every " + (Object)ChatColor.GREEN + "2s" + (Object)ChatColor.GRAY + "."));
        this.set(20, SUtil.getStack((Object)ChatColor.GREEN + "\u2748 Defense " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getDefense().addAll().intValue()), Material.IRON_CHESTPLATE, (short)0, 1, (Object)ChatColor.GRAY + "Defense reduces the damage that", (Object)ChatColor.GRAY + "you take from enemies.", " ", (Object)ChatColor.GRAY + "Damage Reduction: " + (Object)ChatColor.GREEN + Math.round(statistics.getDefense().addAll() / (statistics.getDefense().addAll() + 100.0) * 100.0 * 10.0 / 10.0) + "%", (Object)ChatColor.GRAY + "Effective Health: " + (Object)ChatColor.RED + SUtil.commaify(SUtil.roundTo(statistics.getMaxHealth().addAll() * ((statistics.getDefense().addAll() + 100.0) / 100.0), 1)) + "\u2764"));
        final Dye dye = new Dye();
        dye.setColor(DyeColor.RED);
        this.set(21, SUtil.getStack((Object)ChatColor.RED + "\u2741 Strength " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getStrength().addAll().intValue()), Material.BLAZE_POWDER, (short)0, 1, (Object)ChatColor.GRAY + "Strength increases your base", (Object)ChatColor.GRAY + "melee damage, including punching", (Object)ChatColor.GRAY + "and weapons.", " ", (Object)ChatColor.GRAY + "Base Damage: " + (Object)ChatColor.GREEN + SUtil.commaify(5.0 + statistics.getStrength().addAll() / 5.0)));
        this.set(22, SUtil.getStack((Object)ChatColor.WHITE + "\u2726 Speed " + SUtil.commaify(statistics.getSpeed().addAll() * 100.0), Material.SUGAR, (short)0, 1, (Object)ChatColor.GRAY + "Speed increases your walk speed.", " ", (Object)ChatColor.GRAY + "You are " + (Object)ChatColor.GREEN + (statistics.getSpeed().addAll() * 100.0 - 100.0) + "% " + (Object)ChatColor.GRAY + "faster!"));
        this.set(23, SUtil.getSkullURLStack((Object)ChatColor.BLUE + "\u2623 Crit Chance " + (Object)ChatColor.WHITE + SUtil.commaify(visualcap.intValue()) + "%", "3e4f49535a276aacc4dc84133bfe81be5f2a4799a4c04d9a4ddb72d819ec2b2b", 1, (Object)ChatColor.GRAY + "Crit Chance is your chance to", (Object)ChatColor.GRAY + "deal extra damage on enemies."));
        this.set(24, SUtil.getSkullURLStack((Object)ChatColor.BLUE + "\u2620 Crit Damage " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getCritDamage().addAll() * 100.0) + "%", "ddafb23efc57f251878e5328d11cb0eef87b79c87b254a7ec72296f9363ef7c", 1, (Object)ChatColor.GRAY + "Crit Damage is the amount of", (Object)ChatColor.GRAY + "extra damage you deal when", (Object)ChatColor.GRAY + "landing a critical hit."));
        this.set(25, SUtil.getStack((Object)ChatColor.AQUA + "\u270e Intelligence " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getIntelligence().addAll().intValue()), Material.ENCHANTED_BOOK, (short)0, 1, (Object)ChatColor.GRAY + "Intelligence increases both your", (Object)ChatColor.GRAY + "Mana Pool and the damage of your", (Object)ChatColor.GRAY + "magical items.", " ", (Object)ChatColor.GRAY + "Magic Damage: +" + (Object)ChatColor.AQUA + SUtil.commaify(statistics.getIntelligence().addAll()) + "%", (Object)ChatColor.GRAY + "Mana Pool: " + (Object)ChatColor.AQUA + SUtil.commaify(statistics.getIntelligence().addAll() + 100.0)));
        this.set(28, SUtil.getStack((Object)ChatColor.RED + "\u0e51 Ability Damage " + (Object)ChatColor.WHITE + SUtil.commaify(Math.round((double)statistics.getAbilityDamage().addAll())) + "%", Material.BEACON, (short)0, 1, (Object)ChatColor.GRAY + "Ability Damage is the percentage", (Object)ChatColor.GRAY + "of bonus damage applied to your", (Object)ChatColor.GRAY + "spells!", " ", Sputnik.trans("&7Base Ability Damage: &a") + Math.round(0.5 * Skill.getLevel(User.getUser(player.getUniqueId()).getEnchantXP(), false)) + "%", " ", Sputnik.trans("&7Bonus Ability Damage: &8+&e" + (Math.round((double)statistics.getAbilityDamage().addAll()) - Math.round(0.5 * Skill.getLevel(User.getUser(player.getUniqueId()).getEnchantXP(), false))) + "%")));
        this.set(29, SUtil.getStack((Object)ChatColor.YELLOW + "\u2694 Bonus Attack Speed " + (Object)ChatColor.WHITE + SUtil.commaify(Math.min(100.0, (double)statistics.getAttackSpeed().addAll())) + "%", Material.GOLD_AXE, (short)0, 1, (Object)ChatColor.GRAY + "Bonus Attack Speed decreases the", (Object)ChatColor.GRAY + "time between hits on your", (Object)ChatColor.GRAY + "opponent.", " ", Sputnik.trans("&7Base Attack Speed: &a0%"), " ", Sputnik.trans("&7Bonus Attack Speed: &8+&e" + SUtil.commaify(Math.min(100.0, (double)statistics.getAttackSpeed().addAll())) + "%")));
        this.set(30, SUtil.getStack((Object)ChatColor.DARK_AQUA + "\u03b1 Sea Creature Chance " + (Object)ChatColor.RED + "\u2717", Material.PRISMARINE_CRYSTALS, (short)0, 1, (Object)ChatColor.GRAY + "Sea Creature Chance is your", (Object)ChatColor.GRAY + "chance to catch Sea Creatures", (Object)ChatColor.GRAY + "while fishing."));
        this.set(32, SUtil.getSkullURLStack((Object)ChatColor.LIGHT_PURPLE + "\u2663 Pet Luck " + (Object)ChatColor.RED + "\u2717", "93c8aa3fde295fa9f9c27f734bdbab11d33a2e43e855accd7465352377413b", 1, (Object)ChatColor.GRAY + "Pet Luck increases how many pets", (Object)ChatColor.GRAY + "you find and gives you better", (Object)ChatColor.GRAY + "luck when crafting pets."));
        this.set(31, SUtil.getStack((Object)ChatColor.AQUA + "\u272f Magic Find " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getMagicFind().addAll() * 100.0), Material.STICK, (short)0, 1, (Object)ChatColor.GRAY + "Magic Find increases how many", (Object)ChatColor.GRAY + "rare items you find.", " ", Sputnik.trans("&7Base Magic Find: &a0"), " ", Sputnik.trans("&7Bonus Magic Find: &8+&e" + SUtil.commaify(statistics.getMagicFind().addAll() * 100.0))));
        this.set(33, SUtil.getStack((Object)ChatColor.WHITE + "\u2742 True Protection " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getTrueDefense().addAll()), Material.INK_SACK, (short)15, 1, " ", Sputnik.trans("&7Base True Defense: &a0"), " ", Sputnik.trans("&7Bonus True Defense: &8+&e" + SUtil.commaify(statistics.getTrueDefense().addAll()))));
        this.set(34, SUtil.getStack((Object)ChatColor.RED + "\u2afd Ferocity " + (Object)ChatColor.WHITE + SUtil.commaify(statistics.getFerocity().addAll()), Material.INK_SACK, (short)1, 1, (Object)ChatColor.GRAY + "Ferocity grants percent chance", (Object)ChatColor.GRAY + "to double-strike enemies", (Object)ChatColor.GRAY + "Increments of 100 increases the", (Object)ChatColor.GRAY + "base number of strikes.", " ", Sputnik.trans("&7Base Ferocity: &a0"), " ", Sputnik.trans("&7Bonus Ferocity: &8+&e" + SUtil.commaify(statistics.getFerocity().addAll())), " ", Sputnik.trans("&7Base extra strikes: &c+" + Math.round((float)FerocityCalculation.ferocityStrikeCurrent((int)Math.round((double)statistics.getFerocity().addAll())))), Sputnik.trans("&7Chance for 1 more: &c" + Math.round((double)FerocityCalculation.ferocityPercentNext((int)Math.round((double)statistics.getFerocity().addAll()))) + "%")));
    }
}
